name:
type: drupal9
docroot:
database:
  type: mariadb
  version: "10.5"
mutagen_enabled: true
nodejs_version: "14"
webimage_extra_packages: [build-essential, libnotify-bin, make, python]
hooks:
  post-start: [exec-host: 'ddev db']
